### Typing in python

In [4]:
import typing
types=dir(typing)

print(len(types))

216


In [12]:
from typing import List, Dict, Tuple, Set, Any, Optional,Iterable


#when we want to specify the type of data we are passing to a function we can use the above datatypes

def print_data(data: List[int]|Tuple|Set|Dict) -> Any:
    print(*data)
    return len(data)

# so instead of writing multiple datatypes for the iteration we can use Iterable
# which is a generic type that can accept any iterable 
# data type like list, tuple, set, dict etc.

def process_data(data:Iterable) -> Optional[int]:
    for item in data:
        print(item)
    return len(data)

if __name__=="__main__":
    print_data([1, 2, 3, 4, 5])
    process_data({1, 2, 3, 4, 5})


1 2 3 4 5
1
2
3
4
5


In [17]:
from typing import Sequence

def print_sequence(seq: Sequence) -> None:
    return seq[0]

if __name__=="__main__":
    print_sequence({1, 2, 3, 4, 5})# this will raise an error because set is not a sequence data type.

# when to use sequence?? 
# we can use sequence when we are only slicing and indexing the data and we don't care about the order of the data.

TypeError: 'set' object is not subscriptable

In [2]:
from typing import Protocol
from abc import ABC, abstractmethod 


class Animal(ABC):
    @property
    @abstractmethod
    def legs(self)->int:
        pass
    
    @abstractmethod
    def make_sound(self)->str:
        pass

# so why do we use protocol??
# we use protocol when we want to define a common interface for 
# different classes without using inheritance.
# for example we can have a class snake that makes a sound but it doesn't have legs 
# so it can't inherit from the Animal class but we can define a protocol for 
# it and make it implement the make_sound method.

class Sound(Protocol):
    def make_sound(self) -> str:
        pass

class snake:
    def make_sound(self) -> str:
        return "Hiss"
        
    
class Dog(Animal):
    def make_sound(self) -> str:
        return "Bark"
    @property
    def legs(self) ->int:
        return 4
   
def getanimal_sound(animal: Sound) -> None:
    for sound in animal:
        print(sound.make_sound())
    
if __name__=="__main__":
    dog=Dog()
    snake=snake()
    getanimal_sound([dog, snake])
    

Bark
Hiss


In [ ]:
from typing import Protocol, TypeVar , List, Iterable
from abc import ABC, abstractmethod

T=TypeVar('T', covariant=True)

class Counter(ABC):
    @abstractmethod
    def count(self,str) -> int:
        pass
    
    @abstractmethod
    def count_int(self,data: int) -> int:
        pass
    

class Counter1(Counter):
    def count(self,data: str) -> int:
        return len(data)
    
    def count_int(self,data: int) -> int:
        return self.count(str(data))


class CounterProtocol(Protocol[T]):
    def count(self,str) -> T:
        pass

class Counter2():
    def count(self,data: List)-> int:
        return len(data)
    


def get_count(counter: Iterable[CounterProtocol]) -> int:
    for Counter in counter:
        print(Counter.count("212"))




if __name__=="__main__":
    get_count([Counter1(), Counter2()])


3
3


so we can use the protocol to create our custom dtype and check for a particular need like
length can be measured? can we index it ? can we compare greater than less than etc..

In [3]:
from typing import Protocol, TypeVar, Any

T=TypeVar('T', covariant=True)

class MySequence(Protocol[T]):
    def __getitem__(self, __idx: Any) -> T:
        ...
    
    def __len__(self) -> int:
        ...

def process_sequence(seq: MySequence[str]) -> str:
    if len(seq) > 0:
        return seq[0]
    return "Empty sequence"

In [6]:
from typing import Protocol, TypeVar, Any
from  typing_extensions import Self

class Lessthan(Protocol):
    def __lt__(self,other:Self)->bool:
        pass

T=TypeVar('T',bound=Lessthan)



def find_minimum(a:T,b:T)->bool:
    if a < b:
        return a
    return b


if __name__=="__main__":
    print(find_minimum(3, 5))
    print(find_minimum("apple", "banana"))


3
apple


In [8]:
from dataclasses import dataclass
from typing import Self

@dataclass
class Line:
    xmin:float
    xmax:float
    def __lt__(self,other:Self)->bool:
        return (self.xmax - self.xmin) < (other.xmax - other.xmin)

if __name__=="__main__":
    line1=Line(0, 12)
    line2=Line(0, 10)
    print(max(line1,line2))

Line(xmin=0, xmax=12)


alright let's go with a levels as this note is going random

#### level1 foundational

In [ ]:
#basic annotations

a:int=10
b:str="Hello"
c:float=3.14
d:bool=True
e:Any=None

#these are basic datatypes that we can use to annotate our variables and functions.

In [15]:
#Optional is used when we want to specify that a variable can be of a certain type or None.

from typing import Optional

def greeting(name:Optional[str]=None)->Optional[str]:
    if name is None:
        return "Hello there, welcome to the world of Python!"
    # else:
    #     return f"Hello {name}, welcome to the world of Python!"
    
if __name__=="__main__":
    print(greeting("Alice"))
    print(greeting())

None
Hello there, welcome to the world of Python!


In [ ]:
#Union is used when we want to specify that a variable can be of multiple types.

from typing import Union

def count_of_items(items:Union[str,int])->str:
    return f"The count of items is {items}"

if __name__=="__main__":
    print(count_of_items("Hello"))
    print(count_of_items(12345))
    print(count_of_items(1.6))# this should raise an error when running with mypy

The count of items is Hello
The count of items is 12345
The count of items is 1.6


#### Level 2   Containers and collections

In [ ]:
#collections
from typing import List, Dict, Tuple, Set, Optional

def print_data(data: Dict[str|int,float|int],data2: List[Tuple[str,int]|Tuple[int,int]],data3:Set[float]|None=None)->None:
    for key,value in data.items():
        print(f"{key}: {value}")
    
    for item in data2:
        print(*item)

    if data3 is not None:
        print(*data3)

if __name__=="__main__":
    print_data({"a": 1, "b": 2}, [("x", 10), (20, 30)])

    print_data({"a": 1, "b": 2}, [("x", 10), (20, 30)], {3.14, 2.71})


a: 1
b: 2
x 10
20 30
a: 1
b: 2
x 10
20 30
2.71 3.14


In [44]:
#Containers
from typing import Iterable
from typing import Iterator
from typing import Sequence
from typing import Any

def get_index(data:Sequence,index:int)->Any:
    return data[index]


def iter_data(data:Iterator)->None:
        try:
            while True:
                print(next(data))
        except StopIteration:
            print("End of iteration")

def loop_data(data:Iterable)->None:
    for item in data:
        print(item)

if __name__=="__main__":
    loop_data([1, 2, 3, 4, 5])
    loop_data((1, 2, 3, 4, 5))
    loop_data({1, 2, 3, 4, 5})
    loop_data({"a": 1, "b": 2})
    iter_data(iter([1, 2, 3, 4, 5]))
    print(get_index([1, 2, 3, 4, 5], 2))







1
2
3
4
5
1
2
3
4
5
1
2
3
4
5
a
b
1
2
3
4
5
End of iteration
3


In [47]:
a={"ten":10,"twenty":"20"}
a={"ten":10,20:20}

a[20]

20

In [ ]:
from typing import TypedDict, NotRequired, Optional

class User(TypedDict):
    name:str
    age:int
    email:Optional[str]
    phone:NotRequired[int]


user:User={"name":"Dilip", "age":30}
print(user)

{'name': 'Dilip', 'age': 30}


##### level3 Callables, TypeVar and Generic classes


In [ ]:
from typing import Callable, Sequence, List

#callable is when we want to specify that a variable is a function 

def get_val(values:List[int],index:int)->int:
    return values[index]

def call(func:Callable[[Sequence[int]],int]):
    index=6
    return func([1, 2, 3, 4, 5, 7, 8, 9],index)



if __name__=="__main__":
    print(call(get_val))

8


In [68]:
from typing import TypeVar

# I don’t know the type yet, but it must stay consistent

T=TypeVar('T')

def sample(input:T)->T:
    return input+input


IF=TypeVar('IF', int,float)

def sample2(input:IF)->IF:
    return input*2

class Animal:
    def __init__(self):
        pass
    def make_sound(self)->str:
        return "Some sound"

class Dog(Animal):
    def make_sound(self)->str:
        return "Bark"
    
class Cat(Animal):
    def make_sound(self)->str:
        return "Meow"
    
AnimalType=TypeVar('AnimalType', bound=Animal)

def get_animal_sound(animal:List[AnimalType]):
    for i in animal:
        print(i.make_sound())

if __name__=="__main__":
    print(sample(5))
    print(sample("Hello"))
    get_animal_sound([Dog(), Cat(),Animal()])

10
HelloHello
Bark
Meow
Some sound


Overload is for type checking for example 
if a two functions with same number of params but just the dtype is different
we can use overload to differentiate them just like overloading concept.

In [70]:
from typing import overload

class Concat:
    @overload
    def concat(self,a:str,b:str)->str:
        pass
    
    @overload
    def concat(self,a:int,b:int)->int:
        pass
    
    @overload
    def concat(self,a:List[int],b:List[int])->List[int]:
        pass

    def concat(self,a: int|str|List[int],b:int|str|List[int])->int|str|List[int]:
        return a+b
    
if __name__=="__main__":
    concat=Concat()
    print(concat.concat("Hello ", "World"))
    print(concat.concat(10, 20))
    print(concat.concat([1, 2], [3, 4]))


Hello World
30
[1, 2, 3, 4]


In [ ]:
# *args are more like list of values
# **kwargs are more like dictionary of values

from typing import ParamSpec , TypeVar, Callable

R=TypeVar('R')
P=ParamSpec('P')


def wrapper(func:Callable[P,R])->Callable[P,R]:
    def inner(*args:P.args,**kwargs:P.kwargs) ->R:
        print(args, kwargs)
        return func(*args,**kwargs)
    return inner
    
def add(a:int,b:int)->int:
    
    return a+b

if __name__=="__main__":
    wrapped=wrapper(add)
    print(wrapped(10,b= 20))

(10,) {'b': 20}
30


In [30]:
from sklearn.ensemble import AdaBoostClassifier,RandomForestClassifier,RandomForestRegressor
from sklearn.model_selection import train_test_split

from typing import Protocol
import numpy as np



class Model(Protocol):
    def fit(self,x_train:np.array,y_train:np.array)->None:
        ...
    def predict(self,x_test:np.array)->np.array:
        ...


def evaluate(model:Model,x_test:np.array,y_test:np.array):
    preds=model.predict(x_test)
    return preds

if __name__=="__main__":
    model1=AdaBoostClassifier()
    model2=RandomForestClassifier() 
    model3=RandomForestRegressor()

    x=np.array([1,2,3,4,5,6,7,8,10])
    y=np.array([1,2,3,4,5,6,7,8,10])
    x=x.reshape(-1, 1)
    y=y.reshape(-1)

    print(x,y)

    x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,shuffle=False)

    print(x_train,x_test)
    print(y_train,y_test)

    models=[model1,model2,model3]

    for model in models:
        model.fit(x_train,y_train)
        print(f"model:{model},{y_test} ",evaluate(model,x_test,y_test))






[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [10]] [ 1  2  3  4  5  6  7  8 10]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] [[ 7]
 [ 8]
 [10]]
[1 2 3 4 5 6] [ 7  8 10]
model:AdaBoostClassifier(),[ 7  8 10]  [4 4 4]
model:RandomForestClassifier(),[ 7  8 10]  [6 6 6]
model:RandomForestRegressor(),[ 7  8 10]  [5.67 5.67 5.67]


#### Literal is more like choose the options listed


In [1]:
from typing import Literal

def environment(env:Literal["prod","preprod","UAT","dev"]):
    print(f"{env}")


if __name__=="__main__":
    environment("satoru")#error
    environment("preprod")#success

satoru


so, Final is to define a constant value
and final is to define a constant function which cannot be modified by child class

In [4]:
from typing import final, Final

class User:
    company_name: Final="ABC company"
    def __init__(self,name:str,role:str):
        self.name=name
        self.role=role

    @final
    def user_desc(self):
        print(f"{self.name} is a {self.role} at {self.company_name}")

if __name__=="__main__":
    User("Dilip","Software developer").user_desc()

Dilip is a Software developer at ABC company
